import Vue from "vue";
import { Button } from 'vant';
import { Icon } from 'vant';
import { Form } from 'vant';
import { Field } from 'vant';
import { NavBar } from 'vant';
import { Toast } from 'vant';
import { Tab, Tabs } from 'vant';
import { Cell, CellGroup } from 'vant';
import { List } from 'vant';
import { PullRefresh } from 'vant';
import { ActionSheet } from 'vant';
import { Search } from 'vant';
import { Col, Row } from 'vant';
import { Divider } from 'vant';
import { IndexBar, IndexAnchor } from 'vant';
import { Sidebar, SidebarItem } from 'vant';
import { Grid, GridItem } from 'vant';
import { Tag } from 'vant';
import { Swipe, SwipeItem } from 'vant';
import { TreeSelect } from 'vant';
import { Uploader } from 'vant';
import { Dialog } from 'vant';
import { Picker } from 'vant';
import { DatetimePicker } from 'vant';

Vue.use(DatetimePicker);
Vue.use(Picker);
// 全局注册
Vue.use(Dialog);
Vue.use(Uploader);
Vue.use(TreeSelect);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Tag);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(IndexBar);
Vue.use(IndexAnchor);
Vue.use(Divider);
Vue.use(Col);
Vue.use(Row);
Vue.use(Search);
Vue.use(ActionSheet);
Vue.use(PullRefresh);
Vue.use(List);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Toast);
Vue.use(NavBar);
Vue.use(Form);
Vue.use(Field);
Vue.use(Icon);
Vue.use(Button)
